trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'studenthub'
  containerRegistry: 'pythonlask.azurecr.io'
  dockerRegistryServiceConnection: 'dr-connection'
  azureSubscription: 'rm-connection'
  aksResourceGroup: 'rg-python'
  aksCluster: 'aks-python'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

steps:

- checkout: self

# Debug Repository
- script: |
    echo "Build Sources Directory:"
    echo $(Build.SourcesDirectory)
    ls -R $(Build.SourcesDirectory)
  displayName: 'Verify Repository Files'

# Build Docker Image
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)

# Push Docker Image
- task: Docker@2
  displayName: Push Docker Image
  inputs:
    command: push
    repository: $(imageRepository)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)

# Login to Azure and get AKS credentials
- task: AzureCLI@2
  displayName: Connect to AKS
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials \
        --resource-group $(aksResourceGroup) \
        --name $(aksCluster) \
        --overwrite-existing

# Update Image in deployment.yaml
- script: |
    sed -i "s|pythonlask.azurecr.io/studenthub:latest|$(containerRegistry)/$(imageRepository):$(tag)|g" k8s/deployment.yaml
    cat k8s/deployment.yaml
  displayName: Update Deployment Image

# Deploy Deployment
- task: Kubectl@1
  displayName: Deploy Deployment
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: $(azureSubscription)
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(aksCluster)
    command: apply
    useConfigurationFile: true
    configuration: 'k8s/deployment.yaml'

# Deploy Service
- task: Kubectl@1
  displayName: Deploy Service
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: $(azureSubscription)
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(aksCluster)
    command: apply
    useConfigurationFile: true
    configuration: 'k8s/service.yaml'

# Verify Deployment
- task: Kubectl@1
  displayName: Verify Deployment
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: $(azureSubscription)
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(aksCluster)
    command: get
    arguments: 'pods,svc'
