
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'studenthub'
  containerRegistry: 'pythonlask.azurecr.io'
  dockerRegistryServiceConnection: 'dr-connection'
  azureSubscription: 'rm-connection'
  aksResourceGroup: 'rg-python'
  aksCluster: 'aks-python'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

steps:

- checkout: self

# Build and Push Docker Image
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)

# Update image in deployment.yaml
- task: Bash@3
  displayName: Update Deployment Image
  inputs:
    targetType: 'inline'
    script: |
      sed -i "s|pythonlask.azurecr.io/studenthub:latest|$(containerRegistry)/$(imageRepository):$(tag)|g" k8s/deployment.yaml
      cat k8s/deployment.yaml

# Deploy to AKS using Azure CLI
- task: AzureCLI@2
  displayName: Deploy to AKS
  inputs:
    azureSubscription: 'rm-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials \
        --resource-group rg-python \
        --name aks-python \
        --overwrite-existing

      kubectl apply -f k8s/deployment.yaml
      kubectl apply -f k8s/service.yaml

      kubectl rollout status deployment/studenthub

      kubectl get pods
      kubectl get svc
