services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: studenthub
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:root123@mysql:3306/studentdb

volumes:
  mysql_data:
